version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  db-init:
    restart: no
    build: ./
    command: ./wait-for-postgres.sh db ./db-init
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      HOST: db
      PORT: 5432
      SSL_MODE: disable
      MIGRATION_VERSION: 1.0.0
      COUNT: 1000000
      ANALYTICS_TABLE: anime
      USERS: nekit,lexa
    depends_on:
      - db