version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./migration_scripts:/docker-entrypoint-initdb.d
      - ./db/migration:/db/migration/

  db-init:
    restart: no
    build: ./
    command: ./wait-for-postgres.sh db ./db-init
    env_file:
      - .env
    depends_on:
      - db