version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  db-init:
    restart: no
    build: ./
    command: ./wait-for-postgres.sh db ./db-init
    env_file:
      - .env
    depends_on:
      - db