version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  db-init:
    restart: on-failure
    build: ./
    command: ./wait-for-postgres.sh db ./db-init
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB: postgres
      MIGRATION_VERSION: 1.0.0
    depends_on:
      - db